language: bash

sudo: false

services:
  - docker

env:
  - Dockerfile=v0.12/alpine
  - Dockerfile=v0.12/alpine-onbuild
  - Dockerfile=v0.12/debian
  - Dockerfile=v0.12/debian-onbuild
  - Dockerfile=v1.0/alpine
  - Dockerfile=v1.0/alpine-onbuild
  - Dockerfile=v1.0/debian
  - Dockerfile=v1.0/debian-onbuild

before_script:
  - make image DOCKERFILE=$Dockerfile VERSION=test

script:
  - make test DOCKERFILE=$Dockerfile VERSION=test
